/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GiveRouteImport } from './routes/give'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as LiveRouteImport } from './routes/live'
import { Route as MediaRouteImport } from './routes/media'
import { Route as MinistriesRouteImport } from './routes/ministries'
import { Route as PrayerRouteImport } from './routes/prayer'
import { Route as SermonsRouteImport } from './routes/sermons'
import { Route as TestimoniesRouteImport } from './routes/testimonies'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardEventsRouteImport } from './routes/_authenticated/dashboard/events'
import { Route as AuthenticatedDashboardGalleryRouteImport } from './routes/_authenticated/dashboard/gallery'
import { Route as AuthenticatedDashboardGivingRouteImport } from './routes/_authenticated/dashboard/giving'
import { Route as AuthenticatedDashboardInboxRouteImport } from './routes/_authenticated/dashboard/inbox'
import { Route as AuthenticatedDashboardLiveRouteImport } from './routes/_authenticated/dashboard/live'
import { Route as AuthenticatedDashboardPagesRouteImport } from './routes/_authenticated/dashboard/pages'
import { Route as AuthenticatedDashboardPeopleRouteImport } from './routes/_authenticated/dashboard/people'
import { Route as AuthenticatedDashboardSermonsRouteImport } from './routes/_authenticated/dashboard/sermons'
import { Route as AuthenticatedDashboardTestimoniesRouteImport } from './routes/_authenticated/dashboard/testimonies'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveRoute = GiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistriesRoute = MinistriesRouteImport.update({
  id: '/ministries',
  path: '/ministries',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerRoute = PrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => rootRouteImport,
} as any)
const SermonsRoute = SermonsRouteImport.update({
  id: '/sermons',
  path: '/sermons',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimoniesRoute = TestimoniesRouteImport.update({
  id: '/testimonies',
  path: '/testimonies',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEventsRoute =
  AuthenticatedDashboardEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGalleryRoute =
  AuthenticatedDashboardGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGivingRoute =
  AuthenticatedDashboardGivingRouteImport.update({
    id: '/giving',
    path: '/giving',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInboxRoute =
  AuthenticatedDashboardInboxRouteImport.update({
    id: '/inbox',
    path: '/inbox',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLiveRoute =
  AuthenticatedDashboardLiveRouteImport.update({
    id: '/live',
    path: '/live',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPagesRoute =
  AuthenticatedDashboardPagesRouteImport.update({
    id: '/pages',
    path: '/pages',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPeopleRoute =
  AuthenticatedDashboardPeopleRouteImport.update({
    id: '/people',
    path: '/people',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSermonsRoute =
  AuthenticatedDashboardSermonsRouteImport.update({
    id: '/sermons',
    path: '/sermons',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTestimoniesRoute =
  AuthenticatedDashboardTestimoniesRouteImport.update({
    id: '/testimonies',
    path: '/testimonies',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/give': typeof GiveRoute
  '/leadership': typeof LeadershipRoute
  '/live': typeof LiveRoute
  '/media': typeof MediaRoute
  '/ministries': typeof MinistriesRoute
  '/prayer': typeof PrayerRoute
  '/sermons': typeof SermonsRoute
  '/testimonies': typeof TestimoniesRoute
  '/vision': typeof VisionRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/events': typeof AuthenticatedDashboardEventsRoute
  '/dashboard/gallery': typeof AuthenticatedDashboardGalleryRoute
  '/dashboard/giving': typeof AuthenticatedDashboardGivingRoute
  '/dashboard/inbox': typeof AuthenticatedDashboardInboxRoute
  '/dashboard/live': typeof AuthenticatedDashboardLiveRoute
  '/dashboard/pages': typeof AuthenticatedDashboardPagesRoute
  '/dashboard/people': typeof AuthenticatedDashboardPeopleRoute
  '/dashboard/sermons': typeof AuthenticatedDashboardSermonsRoute
  '/dashboard/testimonies': typeof AuthenticatedDashboardTestimoniesRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/give': typeof GiveRoute
  '/leadership': typeof LeadershipRoute
  '/live': typeof LiveRoute
  '/media': typeof MediaRoute
  '/ministries': typeof MinistriesRoute
  '/prayer': typeof PrayerRoute
  '/sermons': typeof SermonsRoute
  '/testimonies': typeof TestimoniesRoute
  '/vision': typeof VisionRoute
  '/dashboard/events': typeof AuthenticatedDashboardEventsRoute
  '/dashboard/gallery': typeof AuthenticatedDashboardGalleryRoute
  '/dashboard/giving': typeof AuthenticatedDashboardGivingRoute
  '/dashboard/inbox': typeof AuthenticatedDashboardInboxRoute
  '/dashboard/live': typeof AuthenticatedDashboardLiveRoute
  '/dashboard/pages': typeof AuthenticatedDashboardPagesRoute
  '/dashboard/people': typeof AuthenticatedDashboardPeopleRoute
  '/dashboard/sermons': typeof AuthenticatedDashboardSermonsRoute
  '/dashboard/testimonies': typeof AuthenticatedDashboardTestimoniesRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/give': typeof GiveRoute
  '/leadership': typeof LeadershipRoute
  '/live': typeof LiveRoute
  '/media': typeof MediaRoute
  '/ministries': typeof MinistriesRoute
  '/prayer': typeof PrayerRoute
  '/sermons': typeof SermonsRoute
  '/testimonies': typeof TestimoniesRoute
  '/vision': typeof VisionRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/events': typeof AuthenticatedDashboardEventsRoute
  '/_authenticated/dashboard/gallery': typeof AuthenticatedDashboardGalleryRoute
  '/_authenticated/dashboard/giving': typeof AuthenticatedDashboardGivingRoute
  '/_authenticated/dashboard/inbox': typeof AuthenticatedDashboardInboxRoute
  '/_authenticated/dashboard/live': typeof AuthenticatedDashboardLiveRoute
  '/_authenticated/dashboard/pages': typeof AuthenticatedDashboardPagesRoute
  '/_authenticated/dashboard/people': typeof AuthenticatedDashboardPeopleRoute
  '/_authenticated/dashboard/sermons': typeof AuthenticatedDashboardSermonsRoute
  '/_authenticated/dashboard/testimonies': typeof AuthenticatedDashboardTestimoniesRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/give'
    | '/leadership'
    | '/live'
    | '/media'
    | '/ministries'
    | '/prayer'
    | '/sermons'
    | '/testimonies'
    | '/vision'
    | '/dashboard'
    | '/dashboard/events'
    | '/dashboard/gallery'
    | '/dashboard/giving'
    | '/dashboard/inbox'
    | '/dashboard/live'
    | '/dashboard/pages'
    | '/dashboard/people'
    | '/dashboard/sermons'
    | '/dashboard/testimonies'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/give'
    | '/leadership'
    | '/live'
    | '/media'
    | '/ministries'
    | '/prayer'
    | '/sermons'
    | '/testimonies'
    | '/vision'
    | '/dashboard/events'
    | '/dashboard/gallery'
    | '/dashboard/giving'
    | '/dashboard/inbox'
    | '/dashboard/live'
    | '/dashboard/pages'
    | '/dashboard/people'
    | '/dashboard/sermons'
    | '/dashboard/testimonies'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/give'
    | '/leadership'
    | '/live'
    | '/media'
    | '/ministries'
    | '/prayer'
    | '/sermons'
    | '/testimonies'
    | '/vision'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/events'
    | '/_authenticated/dashboard/gallery'
    | '/_authenticated/dashboard/giving'
    | '/_authenticated/dashboard/inbox'
    | '/_authenticated/dashboard/live'
    | '/_authenticated/dashboard/pages'
    | '/_authenticated/dashboard/people'
    | '/_authenticated/dashboard/sermons'
    | '/_authenticated/dashboard/testimonies'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  GiveRoute: typeof GiveRoute
  LeadershipRoute: typeof LeadershipRoute
  LiveRoute: typeof LiveRoute
  MediaRoute: typeof MediaRoute
  MinistriesRoute: typeof MinistriesRoute
  PrayerRoute: typeof PrayerRoute
  SermonsRoute: typeof SermonsRoute
  TestimoniesRoute: typeof TestimoniesRoute
  VisionRoute: typeof VisionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give': {
      id: '/give'
      path: '/give'
      fullPath: '/give'
      preLoaderRoute: typeof GiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministries': {
      id: '/ministries'
      path: '/ministries'
      fullPath: '/ministries'
      preLoaderRoute: typeof MinistriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer': {
      id: '/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof PrayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sermons': {
      id: '/sermons'
      path: '/sermons'
      fullPath: '/sermons'
      preLoaderRoute: typeof SermonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonies': {
      id: '/testimonies'
      path: '/testimonies'
      fullPath: '/testimonies'
      preLoaderRoute: typeof TestimoniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/events': {
      id: '/_authenticated/dashboard/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof AuthenticatedDashboardEventsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/gallery': {
      id: '/_authenticated/dashboard/gallery'
      path: '/gallery'
      fullPath: '/dashboard/gallery'
      preLoaderRoute: typeof AuthenticatedDashboardGalleryRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/giving': {
      id: '/_authenticated/dashboard/giving'
      path: '/giving'
      fullPath: '/dashboard/giving'
      preLoaderRoute: typeof AuthenticatedDashboardGivingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/inbox': {
      id: '/_authenticated/dashboard/inbox'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof AuthenticatedDashboardInboxRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/live': {
      id: '/_authenticated/dashboard/live'
      path: '/live'
      fullPath: '/dashboard/live'
      preLoaderRoute: typeof AuthenticatedDashboardLiveRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/pages': {
      id: '/_authenticated/dashboard/pages'
      path: '/pages'
      fullPath: '/dashboard/pages'
      preLoaderRoute: typeof AuthenticatedDashboardPagesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/people': {
      id: '/_authenticated/dashboard/people'
      path: '/people'
      fullPath: '/dashboard/people'
      preLoaderRoute: typeof AuthenticatedDashboardPeopleRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/sermons': {
      id: '/_authenticated/dashboard/sermons'
      path: '/sermons'
      fullPath: '/dashboard/sermons'
      preLoaderRoute: typeof AuthenticatedDashboardSermonsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/testimonies': {
      id: '/_authenticated/dashboard/testimonies'
      path: '/testimonies'
      fullPath: '/dashboard/testimonies'
      preLoaderRoute: typeof AuthenticatedDashboardTestimoniesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardEventsRoute: typeof AuthenticatedDashboardEventsRoute
  AuthenticatedDashboardGalleryRoute: typeof AuthenticatedDashboardGalleryRoute
  AuthenticatedDashboardGivingRoute: typeof AuthenticatedDashboardGivingRoute
  AuthenticatedDashboardInboxRoute: typeof AuthenticatedDashboardInboxRoute
  AuthenticatedDashboardLiveRoute: typeof AuthenticatedDashboardLiveRoute
  AuthenticatedDashboardPagesRoute: typeof AuthenticatedDashboardPagesRoute
  AuthenticatedDashboardPeopleRoute: typeof AuthenticatedDashboardPeopleRoute
  AuthenticatedDashboardSermonsRoute: typeof AuthenticatedDashboardSermonsRoute
  AuthenticatedDashboardTestimoniesRoute: typeof AuthenticatedDashboardTestimoniesRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardEventsRoute: AuthenticatedDashboardEventsRoute,
    AuthenticatedDashboardGalleryRoute: AuthenticatedDashboardGalleryRoute,
    AuthenticatedDashboardGivingRoute: AuthenticatedDashboardGivingRoute,
    AuthenticatedDashboardInboxRoute: AuthenticatedDashboardInboxRoute,
    AuthenticatedDashboardLiveRoute: AuthenticatedDashboardLiveRoute,
    AuthenticatedDashboardPagesRoute: AuthenticatedDashboardPagesRoute,
    AuthenticatedDashboardPeopleRoute: AuthenticatedDashboardPeopleRoute,
    AuthenticatedDashboardSermonsRoute: AuthenticatedDashboardSermonsRoute,
    AuthenticatedDashboardTestimoniesRoute:
      AuthenticatedDashboardTestimoniesRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  GiveRoute: GiveRoute,
  LeadershipRoute: LeadershipRoute,
  LiveRoute: LiveRoute,
  MediaRoute: MediaRoute,
  MinistriesRoute: MinistriesRoute,
  PrayerRoute: PrayerRoute,
  SermonsRoute: SermonsRoute,
  TestimoniesRoute: TestimoniesRoute,
  VisionRoute: VisionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
